version: '3.8'

services:
  db_service:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  
      - ./init-db:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - app-network

  api_chat:
    image: python:3.10-slim
    user: root
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - PYTHONUNBUFFERED=1
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SMTP_EMAIL=${SMTP_EMAIL}      
      - SMTP_PASSWORD=${SMTP_PASSWORD} 
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./api_chat:/app
      - ./email_agent_mock_data_handoff/email_agent_sandbox/dataset:/app/dataset
      - ./logs:/app/logs
      - ./received_emails:/app/received_emails
    working_dir: /app
    ports:
      - "8000:8000"
    entrypoint: sh /app/entrypoint.sh
    restart: always
    depends_on:
      - db_service
      - ollama
    networks:
      - app-network

  mailserver:
    image: axllent/mailpit
    container_name: mail_sandbox
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: always
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer_gui
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - db_service
    networks:
      - app-network

  ollama:
    container_name: ollama_local
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    restart: unless-stopped
    networks:
      - app-network

volumes:
  db_data:
  ollama_storage:

networks:
  app-network:
    driver: bridge